/*
 * Copyright (C) 2018 yamee
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Gui;
import Gui.MenuCalls.*;
/**
 *
 * @author yamee
 */
public class MainPage extends javax.swing.JPanel {
    
    
    SettingPage settingspage;
    StartNewChat newchat;
    private MainWhatsapp prtPg=MainWhatsapp.getInstance();
    
    public MainPage() {
        initComponents();
        settingspage = new SettingPage(this);
        newchat= new StartNewChat(this);
        prtPg.MainFramePanel.add(settingspage);
        prtPg.MainFramePanel.add(newchat);
        settingspage.setVisible(false);
        newchat.setVisible(false);

        //boolean isEnabled(int index)
    
    
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuForChats = new javax.swing.JPopupMenu();
        NewGroup = new javax.swing.JMenuItem();
        NewBroadCast = new javax.swing.JMenuItem();
        WhatsAppWeb = new javax.swing.JMenuItem();
        StarredMessages = new javax.swing.JMenuItem();
        SettingsChats = new javax.swing.JMenuItem();
        MenuForStatus = new javax.swing.JPopupMenu();
        StatusPrivacy = new javax.swing.JMenuItem();
        SettingsStatus = new javax.swing.JMenuItem();
        MenuForCalls = new javax.swing.JPopupMenu();
        ClearCallLog = new javax.swing.JMenuItem();
        SettingsCalls = new javax.swing.JMenuItem();
        WhatsAppDisplayMainPage = new javax.swing.JLabel();
        MainPagePanel = new javax.swing.JTabbedPane();
        ChatsPanel = new javax.swing.JPanel();
        StartANewChat = new javax.swing.JButton();
        SearchBoxChats = new javax.swing.JTextField();
        MenuChats = new javax.swing.JButton();
        SearchChats = new javax.swing.JButton();
        StatusPanel = new javax.swing.JPanel();
        SearchBoxStatus = new javax.swing.JTextField();
        MyStatusLabel = new javax.swing.JLabel();
        AddStatus = new javax.swing.JButton();
        RecentUpdates = new javax.swing.JLabel();
        ViewedUpdates = new javax.swing.JLabel();
        SearchStatus = new javax.swing.JButton();
        MenuStatus = new javax.swing.JButton();
        CallsPanel = new javax.swing.JPanel();
        SearchBoxCalls = new javax.swing.JTextField();
        MakeaCall = new javax.swing.JButton();
        CallLogLabel = new javax.swing.JLabel();
        MenuCalls = new javax.swing.JButton();
        SearchCalls = new javax.swing.JButton();

        NewGroup.setText("New Group");
        NewGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGroupActionPerformed(evt);
            }
        });
        MenuForChats.add(NewGroup);

        NewBroadCast.setText("New BroadCast");
        MenuForChats.add(NewBroadCast);

        WhatsAppWeb.setText("WhatsAppWeb");
        MenuForChats.add(WhatsAppWeb);

        StarredMessages.setText("Starred Messages");
        MenuForChats.add(StarredMessages);

        SettingsChats.setText("Settings");
        SettingsChats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsChatsActionPerformed(evt);
            }
        });
        MenuForChats.add(SettingsChats);

        MenuForStatus.setComponentPopupMenu(MenuForStatus);

        StatusPrivacy.setText("Status Privacy");
        MenuForStatus.add(StatusPrivacy);

        SettingsStatus.setText("Settings");
        SettingsStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsStatusActionPerformed(evt);
            }
        });
        MenuForStatus.add(SettingsStatus);

        ClearCallLog.setText("Clear Call Log");
        MenuForCalls.add(ClearCallLog);

        SettingsCalls.setText("Settings");
        SettingsCalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsCallsActionPerformed(evt);
            }
        });
        MenuForCalls.add(SettingsCalls);

        setBackground(new java.awt.Color(0, 204, 0));

        WhatsAppDisplayMainPage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WhatsAppDisplayMainPage.setText("WhatsApp");

        StartANewChat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StartANewChat.setText("Start A New Chat");
        StartANewChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartANewChatActionPerformed(evt);
            }
        });

        SearchBoxChats.setText("Search Calls");
        SearchBoxChats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBoxChatsActionPerformed(evt);
            }
        });

        MenuChats.setText("Menu");
        MenuChats.setComponentPopupMenu(MenuForChats);
        MenuChats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChatsActionPerformed(evt);
            }
        });

        SearchChats.setText("Search");
        SearchChats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchChatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChatsPanelLayout = new javax.swing.GroupLayout(ChatsPanel);
        ChatsPanel.setLayout(ChatsPanelLayout);
        ChatsPanelLayout.setHorizontalGroup(
            ChatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatsPanelLayout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addGroup(ChatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartANewChat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatsPanelLayout.createSequentialGroup()
                        .addComponent(SearchBoxChats, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ChatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MenuChats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchChats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ChatsPanelLayout.setVerticalGroup(
            ChatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBoxChats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchChats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuChats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(StartANewChat)
                .addContainerGap())
        );

        MainPagePanel.addTab("Chats", ChatsPanel);

        SearchBoxStatus.setText("Search Status");
        SearchBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBoxStatusActionPerformed(evt);
            }
        });

        MyStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MyStatusLabel.setText("MY STATUS");

        AddStatus.setText("Tap to Add Status Update");

        RecentUpdates.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RecentUpdates.setText("Recent Updates");

        ViewedUpdates.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewedUpdates.setText("Viewed Updates");

        SearchStatus.setText("Search");

        MenuStatus.setText("Menu");
        MenuStatus.setComponentPopupMenu(MenuForStatus);
        MenuStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addComponent(ViewedUpdates)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecentUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        StatusPanelLayout.setVerticalGroup(
            StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addComponent(AddStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RecentUpdates)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(ViewedUpdates)
                        .addGap(111, 111, 111))
                    .addGroup(StatusPanelLayout.createSequentialGroup()
                        .addComponent(MenuStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        MainPagePanel.addTab("Status", StatusPanel);

        SearchBoxCalls.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchBoxCalls.setText("Search Calls");

        MakeaCall.setText("Make a Call");

        CallLogLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CallLogLabel.setText("Call Log");

        MenuCalls.setText("Menu");
        MenuCalls.setComponentPopupMenu(MenuForCalls);
        MenuCalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCallsActionPerformed(evt);
            }
        });

        SearchCalls.setText("Search");

        javax.swing.GroupLayout CallsPanelLayout = new javax.swing.GroupLayout(CallsPanel);
        CallsPanel.setLayout(CallsPanelLayout);
        CallsPanelLayout.setHorizontalGroup(
            CallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CallsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CallsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MakeaCall))
                    .addGroup(CallsPanelLayout.createSequentialGroup()
                        .addComponent(CallLogLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                        .addComponent(SearchBoxCalls, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MenuCalls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchCalls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        CallsPanelLayout.setVerticalGroup(
            CallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CallsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CallsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBoxCalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CallLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCalls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuCalls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(MakeaCall)
                .addContainerGap())
        );

        MainPagePanel.addTab("Calls", CallsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WhatsAppDisplayMainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(MainPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WhatsAppDisplayMainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPagePanel)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBoxChatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBoxChatsActionPerformed
        
            // TODO add your handling code here:
    }//GEN-LAST:event_SearchBoxChatsActionPerformed

    private void MenuChatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChatsActionPerformed
        
            // TODO add your handling code here:
    }//GEN-LAST:event_MenuChatsActionPerformed

    private void SearchBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBoxStatusActionPerformed

    private void MenuStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuStatusActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuStatusActionPerformed

    private void SearchChatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchChatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchChatsActionPerformed

    private void SettingsChatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsChatsActionPerformed
        settingspage.setVisible(true);    
        setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_SettingsChatsActionPerformed

    private void MenuCallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCallsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCallsActionPerformed

    private void NewGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewGroupActionPerformed

    private void SettingsStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsStatusActionPerformed
        settingspage.setVisible(true);    
        setVisible(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_SettingsStatusActionPerformed

    private void SettingsCallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsCallsActionPerformed
        settingspage.setVisible(true);    
        setVisible(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_SettingsCallsActionPerformed

    private void StartANewChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartANewChatActionPerformed
        newchat.setVisible(true);
        setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_StartANewChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStatus;
    private javax.swing.JLabel CallLogLabel;
    private javax.swing.JPanel CallsPanel;
    private javax.swing.JPanel ChatsPanel;
    private javax.swing.JMenuItem ClearCallLog;
    private javax.swing.JTabbedPane MainPagePanel;
    private javax.swing.JButton MakeaCall;
    private javax.swing.JButton MenuCalls;
    private javax.swing.JButton MenuChats;
    private javax.swing.JPopupMenu MenuForCalls;
    private javax.swing.JPopupMenu MenuForChats;
    private javax.swing.JPopupMenu MenuForStatus;
    private javax.swing.JButton MenuStatus;
    private javax.swing.JLabel MyStatusLabel;
    private javax.swing.JMenuItem NewBroadCast;
    private javax.swing.JMenuItem NewGroup;
    private javax.swing.JLabel RecentUpdates;
    private javax.swing.JTextField SearchBoxCalls;
    private javax.swing.JTextField SearchBoxChats;
    private javax.swing.JTextField SearchBoxStatus;
    private javax.swing.JButton SearchCalls;
    private javax.swing.JButton SearchChats;
    private javax.swing.JButton SearchStatus;
    private javax.swing.JMenuItem SettingsCalls;
    private javax.swing.JMenuItem SettingsChats;
    private javax.swing.JMenuItem SettingsStatus;
    private javax.swing.JMenuItem StarredMessages;
    private javax.swing.JButton StartANewChat;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JMenuItem StatusPrivacy;
    private javax.swing.JLabel ViewedUpdates;
    private javax.swing.JLabel WhatsAppDisplayMainPage;
    private javax.swing.JMenuItem WhatsAppWeb;
    // End of variables declaration//GEN-END:variables
}
